
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `actas_observaciones` DISABLE KEYS */;
INSERT INTO `actas_observaciones` (`id_acta`, `fecha_emision`, `inspeccion_id`, `observaciones`) VALUES (1,'2026-10-06 23:08:55.746520',4,'Frenos con eficiencia por debajo del minimo; reparar y reinspeccionar.');
INSERT INTO `actas_observaciones` (`id_acta`, `fecha_emision`, `inspeccion_id`, `observaciones`) VALUES (2,'2026-10-06 23:08:56.265301',6,'Faros desalineados y neumaticos con desgaste irregular.');
INSERT INTO `actas_observaciones` (`id_acta`, `fecha_emision`, `inspeccion_id`, `observaciones`) VALUES (3,'2026-10-06 23:08:56.578601',8,'Emisiones sobre el limite permitido.');
/*!40000 ALTER TABLE `actas_observaciones` ENABLE KEYS */;

/*!40000 ALTER TABLE `certificados_inspeccion` DISABLE KEYS */;
INSERT INTO `certificados_inspeccion` (`id_certificado`, `fecha_emision`, `inspeccion_id`) VALUES (1,'2026-10-06 23:08:54.943181',1);
INSERT INTO `certificados_inspeccion` (`id_certificado`, `fecha_emision`, `inspeccion_id`) VALUES (2,'2026-10-06 23:08:55.220963',2);
INSERT INTO `certificados_inspeccion` (`id_certificado`, `fecha_emision`, `inspeccion_id`) VALUES (3,'2026-10-06 23:08:55.483565',3);
INSERT INTO `certificados_inspeccion` (`id_certificado`, `fecha_emision`, `inspeccion_id`) VALUES (4,'2026-10-06 23:08:56.017023',5);
/*!40000 ALTER TABLE `certificados_inspeccion` ENABLE KEYS */;

/*!40000 ALTER TABLE `clientes` DISABLE KEYS */;
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (1,'45871236','2026-10-06 23:08:54.189466','Carlos Mendoza Rojas');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (2,'40125987','2026-10-06 23:08:54.224394','Ana Torres Quispe');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (3,'72458963','2026-10-06 23:08:54.246303','Luis Fernandez Soto');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (4,'08147529','2026-10-06 23:08:54.266984','Maria Gutierrez Paredes');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (5,'46321587','2026-10-06 23:08:54.286642','Jose Huaman Ccori');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (6,'70236914','2026-10-06 23:08:54.307647','Patricia Salazar Vega');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (7,'10458723','2026-10-06 23:08:54.330990','Transportes Andinos SAC');
INSERT INTO `clientes` (`id_cliente`, `doc_ident`, `fecha_registro`, `nombre`) VALUES (8,'44785210','2026-10-06 23:08:54.353318','Diego Ramirez Luna');
/*!40000 ALTER TABLE `clientes` ENABLE KEYS */;

/*!40000 ALTER TABLE `inspeccion_pruebas` DISABLE KEYS */;
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (1,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (2,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (3,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'FRENOS','OBSERVADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (4,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (5,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'NEUMATICOS','OBSERVADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'LUCES','RECHAZADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (6,'EMISIONES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'NEUMATICOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'DIRECCION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'SUSPENSION','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'LUCES','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (8,'EMISIONES','RECHAZADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (9,'FRENOS','APROBADO');
INSERT INTO `inspeccion_pruebas` (`inspeccion_id`, `prueba`, `resultado`) VALUES (9,'LUCES','APROBADO');
/*!40000 ALTER TABLE `inspeccion_pruebas` ENABLE KEYS */;

/*!40000 ALTER TABLE `inspecciones_tecnicas` DISABLE KEYS */;
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (1,'FINALIZADA',NULL,4,7,1,NULL,'2026-10-06 23:08:54.943181','2026-10-06 23:08:54.684178','APTO','INSPECCION',NULL,1);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (2,'FINALIZADA',NULL,5,7,2,NULL,'2026-10-06 23:08:55.220963','2026-10-06 23:08:55.034786','APTO','INSPECCION',NULL,2);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (3,'FINALIZADA',NULL,6,7,3,NULL,'2026-10-06 23:08:55.483565','2026-10-06 23:08:55.305270','APTO','INSPECCION',NULL,3);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (4,'FINALIZADA',NULL,4,7,4,'Frenos con eficiencia por debajo del minimo; reparar y reinspeccionar.','2026-10-06 23:08:55.746520','2026-10-06 23:08:55.569968','OBSERVADO','INSPECCION',1,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (5,'FINALIZADA',4,4,7,4,NULL,'2026-10-06 23:08:56.017023','2026-10-06 23:08:55.839241','APTO','REINSPECCION',NULL,4);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (6,'FINALIZADA',NULL,5,7,5,'Faros desalineados y neumaticos con desgaste irregular.','2026-10-06 23:08:56.265301','2026-10-06 23:08:56.096103','OBSERVADO','INSPECCION',2,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (7,'EN_PROCESO',6,5,7,5,NULL,NULL,'2026-10-06 23:08:56.357160',NULL,'REINSPECCION',NULL,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (8,'FINALIZADA',NULL,6,NULL,6,'Emisiones sobre el limite permitido.','2026-10-06 23:08:56.578601','2026-10-06 23:08:56.412430','OBSERVADO','INSPECCION',3,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (9,'EN_PROCESO',NULL,4,7,7,NULL,NULL,'2026-10-06 23:08:56.661447',NULL,'INSPECCION',NULL,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (10,'EN_PROCESO',NULL,6,7,8,NULL,NULL,'2026-10-06 23:08:56.769166',NULL,'INSPECCION',NULL,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (11,'REGISTRADA',NULL,5,7,9,NULL,NULL,NULL,NULL,'INSPECCION',NULL,NULL);
INSERT INTO `inspecciones_tecnicas` (`id_inspeccion`, `estado_proceso`, `inspeccion_origen_id`, `inspector_id`, `supervisor_id`, `vehiculo_id`, `observaciones`, `fecha_fin`, `fecha_inicio`, `resultado_condicion`, `tipo_inspeccion`, `acta_id`, `certificado_id`) VALUES (12,'REGISTRADA',NULL,6,NULL,10,NULL,NULL,NULL,NULL,'INSPECCION',NULL,NULL);
/*!40000 ALTER TABLE `inspecciones_tecnicas` ENABLE KEYS */;

/*!40000 ALTER TABLE `rol_permisos` DISABLE KEYS */;
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (1,'USUARIOS_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (1,'ROLES_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (1,'CLIENTES_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (1,'INSPECCIONES_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (2,'CLIENTES_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (2,'VEHICULOS_GESTIONAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (2,'INSPECCIONES_REGISTRAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (3,'INSPECCIONES_INICIAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (3,'PRUEBAS_REGISTRAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (3,'INSPECCIONES_FINALIZAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (4,'INSPECCIONES_CONSULTAR');
INSERT INTO `rol_permisos` (`rol_id`, `permiso`) VALUES (4,'INSPECCIONES_REVISAR');
/*!40000 ALTER TABLE `rol_permisos` ENABLE KEYS */;

/*!40000 ALTER TABLE `roles_acceso` DISABLE KEYS */;
INSERT INTO `roles_acceso` (`id_rol`, `estado_activo`, `nombre_rol`) VALUES (1,_binary '','ROLE_ADMIN');
INSERT INTO `roles_acceso` (`id_rol`, `estado_activo`, `nombre_rol`) VALUES (2,_binary '','ROLE_RECEPCIONISTA');
INSERT INTO `roles_acceso` (`id_rol`, `estado_activo`, `nombre_rol`) VALUES (3,_binary '','ROLE_INSPECTOR');
INSERT INTO `roles_acceso` (`id_rol`, `estado_activo`, `nombre_rol`) VALUES (4,_binary '','ROLE_SUPERVISOR');
/*!40000 ALTER TABLE `roles_acceso` ENABLE KEYS */;

/*!40000 ALTER TABLE `usuarios` DISABLE KEYS */;
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (1,_binary '','RevTech2026!',1,'admin');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (2,_binary '','RevTech2026!',2,'recepcion.lucia');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (3,_binary '','RevTech2026!',2,'recepcion.marco');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (4,_binary '','RevTech2026!',3,'inspector.juan');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (5,_binary '','RevTech2026!',3,'inspector.rosa');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (6,_binary '','RevTech2026!',3,'inspector.pedro');
INSERT INTO `usuarios` (`id_usuario`, `estado_activo`, `password_hash`, `rol_activo_id`, `username`) VALUES (7,_binary '','RevTech2026!',4,'supervisor.elena');
/*!40000 ALTER TABLE `usuarios` ENABLE KEYS */;

/*!40000 ALTER TABLE `vehiculos` DISABLE KEYS */;
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (1,2019,'M1',1,'Toyota','Corolla','ABC-123');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (2,2022,'L',1,'Honda','CB190R','ABD-456');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (3,2016,'M1',2,'Hyundai','Accent','BCD-234');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (4,2018,'N1',3,'Nissan','Frontier','CDE-345');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (5,2020,'M1',4,'Kia','Rio','DEF-456');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (6,2015,'M2',5,'Toyota','Hiace','EFG-567');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (7,2012,'M1',6,'Suzuki','Swift','FGH-678');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (8,2017,'N3',7,'Volvo','FH16','GHI-789');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (9,2014,'M3',7,'Mercedes-Benz','O500','HIJ-890');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (10,2010,'O2',7,'Randon','SR','IJK-901');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (11,2021,'M1',8,'Mazda','CX-5','JKL-012');
INSERT INTO `vehiculos` (`id_vehiculo`, `anio_fabricacion`, `categoria`, `cliente_id`, `marca`, `modelo`, `placa`) VALUES (12,2008,'N2',8,'Hino','300','KLM-123');
/*!40000 ALTER TABLE `vehiculos` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

